name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push images
        run: |
          echo "Pushing gateway image to Docker Hub"
          docker build -t shemich/gateway-service:latest gateway-service
          docker push shemich/gateway-service                         

          echo "Pushing flight-service image to Docker Hub"
          docker build -t shemich/flight-service:latest flight-service
          docker push shemich/flight-service 
          
          echo "Pushing ticket-service image to Docker Hub"
          docker build -t shemich/ticket-service:latest ticket-service
          docker push shemich/ticket-service 
          
          echo "Pushing bonus-service image to Docker Hub"
          docker build -t shemich/bonus-service:latest bonus-service
          docker push shemich/bonus-service 

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"